version: "3.9"

services:
  cassandra:
    image: cassandra:3.11
    container_name: hotel_cassandra
    working_dir: /app/cassandra
    restart: always
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=tourism_cluster
    volumes:
      - cassandra:/var/lib/cassandra
      - ./docker/cassandra/cassandra_schema.cql:/app/cassandra/cassandra_schema.cql
    networks:
      - hotel_net

  init-cql:
    image: cassandra:3.11
    container_name: hotel_cassandra_init
    working_dir: /app/cassandra
    command: bash -c "sleep 45 && cqlsh -u cassandra -p cassandra cassandra 9042 -f /app/cassandra/cassandra_schema.cql && echo 'cassandra_schema.cql executed'"
    volumes:
      - ./docker/cassandra/cassandra_schema.cql:/app/cassandra/cassandra_schema.cql
    depends_on:
      - cassandra
    restart: no
    networks:
      - hotel_net

  postgres:
    container_name: hotel_postgres
    image: postgres:16.6
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: hotel_admin
      POSTGRES_PASSWORD: hotel@123
      POSTGRES_DB: hotel_db
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "5435:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - hotel_net

  oraclenosql:
    image: ghcr.io/oracle/nosql:latest-ce
    container_name: hotel_oraclenosql
    working_dir: /app/kv-24.4.9
    environment:
      - KV_PROXY_PORT=8080
      - HOSTNAME=oraclenosql
    ports:
      - "5436:8080"
    restart: unless-stopped
    volumes:
      - oraclenosql:/kvroot
      - ./docker/oraclenosql/init.sql:/app/kv-24.4.9/init.sql
    command: bash -c "./start-kvlite.sh & sleep 20 && java -jar lib/sql.jar -helper-hosts localhost:5000 -store kvstore < init.sql && echo FINISHED && wait"
    networks:
      - hotel_net

  meltano:
    container_name: hotel_meltano
    image: meltano/meltano
    entrypoint: sleep infinity
    volumes:
      - meltano:/project
      - ./docker/meltano/meltano.yml:/project/meltano.yml
      - ./docker/meltano/dbt_project.yml:/project/dbt_project.yml
      - ./docker/meltano/profiles.yml:/project/profiles.yml
      - ./docker/meltano/models:/project/models
    networks:
      - hotel_net

  hivepostgres:
    container_name: hotel_hive_postgres
    image: postgres:16.6
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore_db
    ports:
      - "5437:5432"
    volumes:
      - hive_postgres:/var/lib/postgresql/data
    networks:
      - hotel_net

  hivemetastore:
    container_name: hotel_hive_metastore
    image: apache/hive:4.0.1
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hivepostgres:5432/metastore_db
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive
    depends_on:
      - hivepostgres
    ports:
      - "9083:9083"
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./hive/postgresql-42.5.1.jar:/opt/hive/lib/postgres.jar
    networks:
      - hotel_net

  hiveserver2:
    container_name: hotel_hiveserver2
    image: apache/hive:4.0.1
    ports:
      - 10000:10000
      - 10002:10002
    environment:
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: -Dhive.metastore.uris=thrift://hivemetastore:9083
      HIVE_AUX_JARS_PATH: /opt/hive/lib/connectors
    depends_on:
      - hivemetastore
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./hive/connectors:/opt/hive/lib/connectors
    networks:
      - hotel_net

  jupyter:
    container_name: jupyter
    image: jupyter/minimal-notebook:2023-10-20
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    volumes:
      - ./jupyter:/home/jovyan/work
    working_dir: /home/jovyan/work
    ports:
      - 8888:8888
    networks:
      - hotel_net

  # hadoop-namenode:
  #   image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
  #   container_name: hotel_hadoop_namenode
  #   environment:
  #     - CLUSTER_NAME=test-hadoop
  #     - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
  #     - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
  #     - HDFS_CONF_dfs_permissions_enabled=false
  #   ports:
  #     - 9870:9870
  #     - 9000:9000
  #   volumes:
  #     - hadoop_namenode:/hadoop/dfs/name
  #   networks:
  #     - hotel_net

  # hadoop-datanode:
  #   image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
  #   container_name: hotel_hadoop_datanode
  #   environment:
  #     - CLUSTER_NAME=test-hadoop
  #     - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
  #     - HDFS_CONF_dfs_permissions_enabled=false
  #   depends_on:
  #     - hadoop-namenode
  #   volumes:
  #     - hadoop_datanode:/hadoop/dfs/data
  #   networks:
  #     - hotel_net

volumes:
  postgres:
  oraclenosql:
  cassandra:
  meltano:
  hive_postgres:
  warehouse:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hotel_net:
    driver: bridge
