services:
  cassandra:
    image: cassandra:3.11
    container_name: hotel_cassandra
    restart: always
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=tourism_cluster
    volumes:
      - cassandra:/var/lib/cassandra

  postgres:
    container_name: hotel_postgres
    image: postgres:16.6
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: hotel_admin
      POSTGRES_PASSWORD: hotel@123
      POSTGRES_DB: hotel_db
    ports:
      - "5435:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  oraclenosql:
    image: ghcr.io/oracle/nosql:latest-ce
    container_name: hotel_oraclenosql
    environment:
      - KV_PROXY_PORT=8080
      - HOSTNAME=oraclenosql
    ports:
      - "5436:8080"
    restart: unless-stopped
    volumes:
      - oraclenosql:/kvroot

  meltano:
    container_name: hotel_meltano
    image: meltano/meltano
    entrypoint: sleep infinity
    volumes:
      - meltano:/project

  hivepostgres:
    container_name: hotel_hive_postgres
    image: postgres:16.6
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore_db
    ports:
      - "5437:5432"
    volumes:
      - hive_postgres:/var/lib/postgresql/data

  hivemetastore:
    container_name: hotel_hive_metastore
    image: apache/hive:4.0.1
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hivepostgres:5432/metastore_db
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive
    depends_on:
      - hivepostgres
    ports:
      - "9083:9083"
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./hive/postgresql-42.5.1.jar:/opt/hive/lib/postgres.jar

  hiveserver2:
    container_name: hotel_hiveserver2
    image: apache/hive:4.0.1
    ports:
      - 10000:10000
      - 10002:10002
    environment:
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: -Dhive.metastore.uris=thrift://hivemetastore:9083
      HIVE_AUX_JARS_PATH: /opt/hive/lib/ext_kv
    depends_on:
      - hivemetastore
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./hive/connectors/oraclenosql:/opt/hive/lib/ext_kv

  jupyter:
    container_name: jupyter
    image: jupyter/minimal-notebook:2023-10-20
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    volumes:
      - ./jupyter:/home/jovyan/work
    working_dir: /home/jovyan/work
    ports:
      - 8888:8888

volumes:
  postgres:
  oraclenosql:
  cassandra:
  meltano:
  hive_postgres:
  warehouse:
