name: hotel_elt
version: '1.0'
config-version: 2

profile: hotel_elt

target-path: target
clean-targets:
  - target
  - dbt_modules

model-paths:
  - models

models:
  hotel_elt:
    +schema: analytics
    +materialized: view

# Les modèles seront placés dans /meltano/dbt/models/ 