hotel_elt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: hotel_postgres
      user: hotel_admin
      password: hotel@123
      port: 5432
      dbname: hotel_db
      schema: analytics
      threads: 2 